version: '3.8'

services:
  voicesentinel-processor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: voicesentinel-processor
    ports:
      - "28472:28472"
    volumes:
      - ./config.json:/app/config.json:ro
      - ./models:/app/models
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      # Remove thread envs if not needed
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:28472/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    cap_add:
      - SYS_NICE
    ulimits:
      nofile: 65536
      nproc: 8192